export const DEFAULT_REDACT_PATHS = [
  "req.headers.authorization",
  "req.headers.cookie",
  "req.headers['x-api-key']",
  "headers.authorization",
  "headers.cookie",
  "headers['x-api-key']",
  "*.password",
  "*.passwordHash",
  "*.token",
  "*.accessToken",
  "*.refreshToken",
  "*.jwt",
  "*.secret",
  "*.otp",
  "*.code",
  "*.apiKey",
  "password",
  "passwordHash",
  "token",
  "accessToken",
  "refreshToken",
  "jwt",
  "secret",
  "otp",
  "code",
  "apiKey",
];

export const REDACT_CENSOR = "[REDACTED]";
