
# Create development builds
#
# Builds Android and iOS development builds for devices and simulators.
# Learn more: https://docs.expo.dev/develop/development-builds/introduction/
#
# Created by EAS CLI v24.7.0

name: Create development builds

on:
  push:
    branches:
      - main
    paths:
      # Trigger only when files in mobile or its shared dependencies change
      - apps/mobile/**
      - packages/schemas/**
      - packages/types/**
      - pnpm-lock.yaml
          
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
